from __future__ import annotations as _annotations

from ._version import __version__
from .agent_source import AgentFactory, AgentSource, FactoryAgentSource, StaticAgentSource
from .agent_types import RuntimeAgent
from .approvals import ApprovalBridge, NativeApprovalBridge
from .bridges import (
    AnthropicCompactionBridge,
    BufferedCapabilityBridge,
    CapabilityBridge,
    HistoryProcessorBridge,
    HistoryProcessorCallable,
    HistoryProcessorContextual,
    HistoryProcessorPlain,
    HistoryProcessorWithContextAsync,
    HistoryProcessorWithContextSync,
    HookBridge,
    ImageGenerationBridge,
    IncludeToolReturnSchemasBridge,
    McpBridge,
    McpCapabilityBridge,
    McpServerDefinition,
    McpToolDefinition,
    OpenAICompactionBridge,
    PlanGenerationType,
    PrefixToolsBridge,
    PrepareToolsBridge,
    PrepareToolsMode,
    SetToolMetadataBridge,
    ThinkingBridge,
    ThreadExecutorBridge,
    ToolsetBridge,
    WebFetchBridge,
    WebSearchBridge,
)
from .builders import AgentBridgeBuilder, AgentBridgeContributions
from .config import AdapterConfig
from .hook_projection import HookEvent, HookProjectionMap
from .host import (
    ClientFilesystemBackend,
    ClientHostContext,
    ClientTerminalBackend,
    FilesystemBackend,
    HostAccessDisposition,
    HostAccessPolicy,
    HostCommandEvaluation,
    HostPathEvaluation,
    HostRisk,
    TerminalBackend,
)
from .models import AdapterModel
from .projection import (
    BuiltinToolProjectionMap,
    CompositeProjectionMap,
    FileSystemProjectionMap,
    ProjectionMap,
    WebToolProjectionMap,
    compose_projection_maps,
)
from .projection_helpers import (
    DEFAULT_TEXT_TRUNCATION_MARKER,
    caution_for_command,
    caution_for_path,
    format_code_block,
    format_diff_preview,
    format_terminal_status,
    single_line_summary,
    truncate_lines,
    truncate_text,
)
from .providers import (
    ApprovalStateProvider,
    ConfigOption,
    ConfigOptionsProvider,
    ModelSelectionState,
    ModeState,
    NativePlanPersistenceProvider,
    PlanProvider,
    PromptModelOverrideProvider,
    SessionModelsProvider,
    SessionModesProvider,
)
from .runtime.hook_introspection import RegisteredHookInfo, list_agent_hooks
from .runtime.server import create_acp_agent, run_acp
from .session.state import AcpSessionContext, JsonValue
from .session.store import FileSessionStore, MemorySessionStore, SessionStore
from .testing import BlackBoxHarness, RecordingACPClient, UpdateRecord, agent_message_texts

__all__ = (
    "AcpSessionContext",
    "AgentFactory",
    "AgentSource",
    "ApprovalBridge",
    "ApprovalStateProvider",
    "AdapterConfig",
    "AdapterModel",
    "AgentBridgeBuilder",
    "AgentBridgeContributions",
    "AnthropicCompactionBridge",
    "BufferedCapabilityBridge",
    "BlackBoxHarness",
    "BuiltinToolProjectionMap",
    "CapabilityBridge",
    "ClientFilesystemBackend",
    "ClientHostContext",
    "ClientTerminalBackend",
    "ConfigOption",
    "ConfigOptionsProvider",
    "CompositeProjectionMap",
    "compose_projection_maps",
    "caution_for_command",
    "caution_for_path",
    "DEFAULT_TEXT_TRUNCATION_MARKER",
    "FileSessionStore",
    "FileSystemProjectionMap",
    "FactoryAgentSource",
    "FilesystemBackend",
    "HostAccessDisposition",
    "HostAccessPolicy",
    "HostCommandEvaluation",
    "HostPathEvaluation",
    "HostRisk",
    "HistoryProcessorCallable",
    "HistoryProcessorBridge",
    "HistoryProcessorContextual",
    "HistoryProcessorPlain",
    "HistoryProcessorWithContextAsync",
    "HistoryProcessorWithContextSync",
    "HookEvent",
    "HookProjectionMap",
    "HookBridge",
    "ImageGenerationBridge",
    "IncludeToolReturnSchemasBridge",
    "JsonValue",
    "list_agent_hooks",
    "MemorySessionStore",
    "McpCapabilityBridge",
    "McpBridge",
    "McpServerDefinition",
    "McpToolDefinition",
    "ModeState",
    "ModelSelectionState",
    "NativeApprovalBridge",
    "NativePlanPersistenceProvider",
    "OpenAICompactionBridge",
    "PlanGenerationType",
    "PlanProvider",
    "PrefixToolsBridge",
    "ProjectionMap",
    "PromptModelOverrideProvider",
    "format_code_block",
    "format_diff_preview",
    "format_terminal_status",
    "PrepareToolsBridge",
    "PrepareToolsMode",
    "RegisteredHookInfo",
    "RecordingACPClient",
    "RuntimeAgent",
    "SetToolMetadataBridge",
    "ThinkingBridge",
    "ThreadExecutorBridge",
    "ToolsetBridge",
    "WebFetchBridge",
    "WebSearchBridge",
    "WebToolProjectionMap",
    "SessionStore",
    "SessionModelsProvider",
    "SessionModesProvider",
    "StaticAgentSource",
    "single_line_summary",
    "TerminalBackend",
    "truncate_lines",
    "truncate_text",
    "UpdateRecord",
    "__version__",
    "agent_message_texts",
    "create_acp_agent",
    "run_acp",
)
